### ISSUE TITLE
或许可以写个对应的复原bat？

### ISSUE THREAD

**Issue by youyinnn** [szzhiyang/PerfectWindows#1]
万一哪天我又想用小娜了呢？

**Comment by szzhiyang** [comment]
您试试再运行一遍那个名为 Cortana 的批处理，Cortana 就复原了，这是我的创意。

刚才我更新了批处理的运作逻辑，以尽可能减少 UAC 确认次数和 Windows 重启次数，欢迎您再次下载体验！
