### ISSUE TITLE
自动节省电量

### ISSUE THREAD

**Issue by Mrliduanyang** [szzhiyang/PerfectWindows#10]
自动节省电量那个，系统自带设置完全可以满足
![tim 20180213214051](https://user-images.githubusercontent.com/18399238/36152643-a37d7284-1106-11e8-9d70-245f88cf9570.png)

**Comment by szzhiyang** [comment]
是的，但是这里的节电模式仅会限制后台活动（准确地说，就是停止大部分计划任务）和限制推送通知，节电效果十分局限。

**Smart Power Plan** 不仅会设置节电模式，还会调整电源计划。您不妨安装 **Smart Power Plan** 后观察一下系统的高级电源设置（在控制面板里），这样您就能理解您为什么需要 **Smart Power Plan** 了。:smile:

另外，Windows 7 和 Windows 8.1 并没有节电模式。因此，这两个操作系统的用户很需要 **Smart Power Plan** 。:smile:

感谢您的支持！:smile:
