### ISSUE TITLE
[Power Keys] 原按键功能失效

### ISSUE THREAD

**Issue by xunzhou** [szzhiyang/PerfectWindows#13]
文本编辑，网页浏览的情况下原按键功能均无法使用，可否考虑用组合键替代？
临时解决方案为使用小键盘的Home/End等功能键。不知是否因为键位映射的方式无法实现组合键？

**Comment by xunzhou** [comment]
这个[Keyboard Scan Code Specification - Microsoft](https://download.microsoft.com/download/1/6/1/161ba512-40e2-4cc9-843a-923143f3456c/scancode.doc)第7页提到了两/三键组合，不过不是很清楚如何写这个"Scancode Map"的hex，还请指教。

**Comment by szzhiyang** [comment]
您好，目前我所采用的键盘映射方法无法实现组合键映射，我正在学习 AutoHotkey 以实现组合键映射，敬请期待！:smile:

事实上，几乎所有浏览器都可以通过按 <kbd>Space</kbd> 来向下翻页，按 <kbd>Shift</kbd> + <kbd>Space</kbd> 来向上翻页，您不妨现在就尝试一下吧！:smile:
