### ISSUE TITLE
下载问题

### ISSUE THREAD

**Issue by freesoft0000** [szzhiyang/PerfectWindows#14]
releases提供完整打包下载即可。目前批处理不要一个一个的下载，不方便。

**Comment by szzhiyang** [comment]
当我看到您的意见时，我好感动，因为这意味着您需要我的好几个批处理。 :smile:

我的想法是，需要什么就下载什么，而不需要的永远都不会来到电脑上。

事实上，绝大部分人只需要其中的一两个批处理。如果他们为了获得其中的一两个批处理而必须打个包再下载十几个批处理，再从压缩包的十几个批处理中找到自己想要的一两个，那就有些复杂了。

往后我还会往这里放置更多的批处理或 .exe 文件。我担心大家会难以从一个包含大量批处理的压缩包中找到自己真正需要的东西。

希望您能理解我的意思，谢谢。 :smile:

**Comment by freesoft0000** [comment]
多谢了！
关键这些批处理文件太小了。不是大文件。单独下载和打包一起下载基本上没有什么区别。
一般使用者也都有些电脑基础，没有电脑基础的也不会使用这些，或者连浏览这个网站的机会都没有。
怎么整理还是你个人的事情，毕竟是你个人的项目。你权衡怎么好就怎么做。
最后祝新年快乐！

**Comment by freesoft0000** [comment]
还有一点，也许说不定什么时候国内访问就比较困难了。所以一般我都是下载到硬盘保存的。保险。

**Comment by szzhiyang** [comment]
@freesoft0000 您是最早关注并支持我的创意的朋友，首先我想借此机会向您表达我最诚挚的敬意和感谢！


也祝您新年快乐，心想事成！


我目前的主要创新和重心都倾注在 **Power Keys** 上了，因为其他批处理都已经完全定型了。对于这些定型的批处理，您只用下载这一次就够了。


您有所不知，受我知乎文章的影响，每天也会相当多的 Windows 小白朋友来这里下载 **Anti Windows Update** 来禁用 Windows 10 自动更新，他们也只需要这一个批处理。如果打包下载的话，他们会不知所措的。这也是我采取单独下载的机制的原因。


我现在急需点子和创意，希望在日后能跟您有更深的交流和探讨。

**Comment by vinjn** [comment]
很好很强大

**Comment by freesoft0000** [comment]
好的，知道了。
另外，批处理目前编码有点小问题。换行符是unix的，改为windows的就好了。

**Comment by szzhiyang** [comment]
@freesoft0000 想请教一下该怎么换啊？我是用 **VS Code** 编写的批处理。

**Comment by szzhiyang** [comment]
@vinjn 感谢您的支持和鼓励！:smile:

**Comment by pzhlkj6612** [comment]
我知道notepad plus plus能换。。。vscode没用过不知道了。

**Comment by szzhiyang** [comment]
@pzhlkj6612 好的，谢谢您！ 😃

**Comment by freesoft0000** [comment]
everedit、notepad++、Notepad2、UltraEdit 都可以

**Comment by freesoft0000** [comment]
批处理文件修改注册表的部分都可以使用reg命令完成。没有必要再复制%0为.reg文件，生成临时文件后再使用regedit导入。

**Comment by szzhiyang** [comment]
@freesoft0000 可是当需要改掉的注册表太多的时候，用 reg 命令就相当麻烦了。

将 .reg 文件和 .bat 文件混合起来也是我的创意。:joy:

**Comment by q9542958** [comment]
vscode 换行符在右下角有个 LF CRLF 切换就是了

另外 windows 的 git 提交时候有个全局配置是会把提交到服务器的文件自动改为 LF 换行符的，输入 git list -l 看到参数里面有 core.autocrlf=true 就是了

**Comment by szzhiyang** [comment]
@q9542958 好的，谢谢您，学习了！:smile:
