### ISSUE TITLE
Fail to stop updating

### ISSUE THREAD

**Issue by wukongtea** [szzhiyang/PerfectWindows#18]
最近又自动更新了，好像是office自动更新了，没出现易升。
![1](https://user-images.githubusercontent.com/25115961/38181449-80085470-3665-11e8-9111-52490c41331a.png)

**Comment by szzhiyang** [comment]
奇怪，我的 Windows 自我上次手动更新以来一直都没有自动更新啊。 😕 

![winver](https://user-images.githubusercontent.com/30952626/38184722-310234b0-367c-11e8-8eb6-a6bf67bd768e.png)

![wu](https://user-images.githubusercontent.com/30952626/38184729-39d6d1fe-367c-11e8-8ea4-79e1693f356e.png)

您能向我提供更多的信息吗？比如系统日志、服务、计划任务等等。

**Comment by wukongtea** [comment]
系统日志  怎么导出来啊？ 

![2](https://user-images.githubusercontent.com/25115961/38193319-20823ad6-36a4-11e8-9649-e796786b1b81.png)

![3](https://user-images.githubusercontent.com/25115961/38193325-258a89c0-36a4-11e8-9557-ec6ca1bc23a0.png)
![4](https://user-images.githubusercontent.com/25115961/38193328-27ee42f6-36a4-11e8-85da-fd2c2b706e87.png)

**Comment by szzhiyang** [comment]
@wukongtea 您好，我更新了 **Anti Windows Update**，它现在可以卸载易升了。
