### ISSUE TITLE
建议把配置文件保存到程序目录里

### ISSUE THREAD

**Issue by visualwind** [szzhiyang/PerfectWindows#19]
重装系统时不用特地备份

**Comment by szzhiyang** [comment]
@visualwind 事实上我在制作这个软件之初就考虑到了这个问题。然而，思来想去，我觉得还是应该把配置文件存储在 `%LocalAppData%` 中，因为这是几乎所有软件都在遵循的规矩，**Power Keys** 当然也不能例外。
