### ISSUE TITLE
我的c盘有的文件夹显示不了 也没隐藏

### ISSUE THREAD

**Issue by youyinnn** [szzhiyang/PerfectWindows#2]
如题  我的Programs File文件夹没了但是在地址栏里敲地址是可以访问到的 是老哥你的工具弄的嘛

**Comment by youyinnn** [comment]
还有其他的一些data文件夹都看不到了…

**Comment by szzhiyang** [comment]
你好，这是一个 Feature，目的是让 Windows 更加平易近人。

如果你需要频繁访问这些文件夹或子文件夹，建议你为它们建立快捷方式以便访问，谢谢。

**Comment by hhu-cs433216** [comment]
那怎么恢复呢？，C盘的文件之前没做处理，现在进不去了

**Comment by hhu-cs433216** [comment]
attrib  命令，，打开看了一下，已经恢复了，感谢大佬的命令

**Comment by szzhiyang** [comment]
@hhu-cs433216 我已经更新了批处理。只需更新批处理即可让这些文件夹的显示状态恢复。:smile:

**Comment by szzhiyang** [comment]
@hhu-cs433216 很抱歉给您造成不便。
