### ISSUE TITLE
我下载后双击就出现拒绝以管理员身份运行，该怎样设置权限呢？

### ISSUE THREAD

**Issue by imspider** [szzhiyang/PerfectWindows#22]
如题

**Comment by szzhiyang** [comment]
@imspider **Power Keys** 是个应用启动器，必然不能以管理员身份运行，否则由它启动的应用程序都将以管理员身份运行，后果不堪设想。

麻烦您将 Windows 的 UAC （用户账户控制）设置重新调整为默认级别后重启电脑，再运行 **Power Keys**，谢谢。
