### ISSUE TITLE
热键失灵

### ISSUE THREAD

**Issue by tianxingzhishang** [szzhiyang/PerfectWindows#23]
开了有一会后，原本windows的快捷键就失灵了，关掉后就好了，你用的时候有这个问题吗

**Comment by szzhiyang** [comment]
@tianxingzhishang 没有遇到过。

请问您可以具体描述一下您是在做出什么操作后失灵的吗？

另外，任何情况下您都可以按 `Win + F5` 来重启 Power Keys。重启 Power Keys 可以解决几乎所有失灵问题。

**Comment by tianxingzhishang** [comment]
我没注意具体什么操作后出现问题，等下我用的时候注意下

**Comment by szzhiyang** [comment]
@tianxingzhishang 好的，非常感谢。

**Comment by szzhiyang** [comment]
@tianxingzhishang 您好，请删除旧版并重新下载使用最新版本，看看问题有没有解决。

**Comment by tianxingzhishang** [comment]
好，我再试一段时间

**Comment by szzhiyang** [comment]
@tianxingzhishang 如果您发现最新版本的 **Power Keys** 仍然存在问题，请重新打开该 issue，谢谢。
