### ISSUE TITLE
新功能建议

### ISSUE THREAD

**Issue by qianjigit** [szzhiyang/PerfectWindows#24]
感谢作者的作品，关注  Power Keys 很长时间了，现在用的 Capslock+，部分功能觉得很赞，比如 TabScript  WinBind 希望可以整合一下
  
**Capslock+** 
[官网：Capslock+](http://cjkis.me/capslock+/)
 [github : wo52616111/capslock-plus](https://github.com/wo52616111/capslock-plus)

另外，请问在  Power Keys 中，像 Ditto 和 Snipaste 这类应用应该怎样操作才能更有效率，谢谢！

**Comment by szzhiyang** [comment]
@qianjigit 非常感谢您的支持，**Power Keys** 事实上就是一款糅合了我自己的创意以及 **CapsLock+** 的核心功能并刨除了脚本编辑等不利于小白使用的功能的产品。**Power Keys** 比起 **CapsLock+** 更加可贵的特点就是它所使用的快捷键都非常形象、合理、易记、人性化，您可以观察到 **Power Keys** 所使用的快捷键全是两个按键的组合，而不是三个甚至四个。更重要的是，**Power Keys** 还是个 Launcher（启动器）。另外，它还没有配置文件、命令行等晦涩难懂的概念，对小白相当友好。

之所以一直没有给 **Power Keys** 加入涉及脚本编辑的功能（比如 TabScript），主要是因为 AutoHotkey 的语法已经足够简单强大了。我是绝对不会让用户耽误自己的宝贵时间来学习我自创的语法的，因为将这些时间花在学习 AutoHotkey 语法而不是我的语法上显然更有意义。

之所以没有加入类似 WinBind 的功能是因为 Windows 原生的 `Win + 数字` 快捷键已经足够好用。

**Power Keys** 有个独家功能就是简化修饰键，就是把 `Ctrl + Shift` 捆成 `Esc`，把 `Ctrl + Alt` 捆成 `Tab`，把 `Ctrl + Shift + Alt` 捆成 `Caps Lock`，这是我的原创。得益于此，无论有多复杂、多难按的快捷键，您都可以不费吹灰之力按下，是 **Ditto** 和各种专业软件（比如 **Photoshop**）最佳的拍档。

另外还有个用 `功能键 + Print Screen` 拉起截图软件功能的功能也是我原创。配合 **ShareX** （**ShareX 才是真正高效的截图工具，因为它支持自定义截图工作流，相比之下，Snipaste 真的很渺小**）等截图软件，您甚至可以用 `F1 + Print Screen` 呼出全屏截图、用 `F2 + Print Screen` 呼出窗口截图、用 `F3 + Print Screen` 呼出矩形截图、用 `F4 + Print Screen` 呼出滚动截图、用 `F5 + Print Screen` 呼出屏幕录制、用 `F6 + Print Screen` 呼出 GIF 屏幕录制、用 `F7 + Print Screen` 呼出屏幕拾色器、用 `F8 + Print Screen` 呼出屏幕尺子等一切与截图相关的功能，您再也不必担心这些截图功能的快捷键不够用了。

**Comment by qianjigit** [comment]
Print Screen 这个键距离有点远？ 也可能是我手指比较短  - - 
  
TabScript 是属于可以自定义的吧？

或者我更应该先用下再给反馈。

感谢您的开源 @szzhiyang

**Comment by qianjigit** [comment]
五笔打字，空格上屏会有一定的影响，特别是打快了的话，会跳错乱的字，影响输入，而且比较明显的是输入字的时候，会有小小的显示卡顿。

**Comment by szzhiyang** [comment]
@qianjigit 您好，我刚才根据您的反馈改进了 **Power Keys** 。

现在，如果您在注销 Windows 前通过按 `Win + F4` 退出了 **Power Keys**，则它将不会在下次登录 Windows 时自启。

至于空格键的问题，目前本人并没有察觉到，可能是因为我打字不如您那么快吧。 😂 不过，在目前这种 按键机制下，我很难解决空格略微延迟的问题。然而，把空格键当修饰键，在打字时按起来显然比 **CapsLock+**  顺手得多，因为在打字过程中手指根本就不用移动。 😂

**Comment by qianjigit** [comment]
@szzhiyang 谢谢。

空格键的话，快和慢确实会有明显区别，按快了就不是首字上屏了，而是后面的或者出来一串字，是否可以加个激活 / 取消激活的键，默认不激活，需要使用特殊功能再激活，有点和 vim 类似

**Comment by szzhiyang** [comment]
@qianjigit 您好，我刚才又改进了 **Power Keys** 的空格键响应逻辑 😂 ，还找了我打字飞快 ✈️ 的舍友拿机械硬盘 ⌨️ 测试了最新的版本。测试表明改进的效果奇佳 ⭐️ ，快来更新试试吧！ 😄 

我真的好感动  😭 ，从来没有人这么看重我的项目，谢谢您！ 🙏

**Comment by szzhiyang** [comment]
@qianjigit 

**Power Keys** 更新方法：

1. 按 `Win + F4` 退出旧的的 **Power Keys**。
2. 下载并运行新的 **Power Keys**。

注意事项：

* 测试 **Power Keys** 时，请退出 **CapsLock+** 以排除干扰因素。

希望您提供的更多信息：

* 您正在使用的输入法软件的生产厂商（Windows 自带？搜狗？百度？QQ？）

**Comment by jiaoting** [comment]
哥们，能否参考Capslock+的上下左右的按键布局，目前的按键布局实在是太难记了，特别容易忘

**Comment by qianjigit** [comment]
@szzhiyang 

最新版本实际测试，问题依旧。

系统：Win10 LTSB 2016
输入法：极致五笔

例如，输入「会不会」，输入快了会变成「会法」，「就是」只出「就」，注意，打的是单字，不是词，还出现过打了一长段话，突然全选，因为是同时在敲字，所以整段话被覆盖了。

我不知道您舍友是不是打的五笔，五笔空格上屏的频率非常非常高，打慢了还好，打快了输入明显错乱，我觉得还是有必要设置个特殊功能按键来激活空格的状态，否则根本不能拿来日常使用。

还有，关于 WinBind 的功能，看似和 windows 本身的重复，但实际使用是不一样的，WinBind 可以自由绑定窗口，默认不用固定在任务栏，场景举例：一些个人常用的特殊软件，不希望固定在任务栏的，或者多虚拟桌面使用，部分应用默认不放任务栏占位置的。

**Comment by szzhiyang** [comment]
@qianjigit 非常感谢您的建议，我现在不再打空格键的主意了，而是把目光放在了右侧的 `Alt` 键上（左侧的 `Alt` 键不受任何影响）。现在，您在打字时只需将右手的大拇指向里挪动一下下就可以轻松挪动光标或者选定文本，就是这个意思：

<img width="578" alt="chrome_2018-04-17_13-45-37" src="https://user-images.githubusercontent.com/30952626/38850822-b2101b7e-4245-11e8-9b90-0f50a329588c.png">

**……**

由于打字时大拇指所处的区域更加空旷，并且大拇指比小拇指更加灵活，所以用起来应该会比 **CapsLock+** 顺手一些。

类似 WinBind 的功能我会再考虑一下。

**Comment by szzhiyang** [comment]
@jiaoting 我安排的键位有着与 **CapsLock+** 完全不同的排布逻辑。由于您已经用惯了 **CapsLock+**，不习惯我的键位是再正常不过的事。

另外，我是 **Power Keys** 的作者，不是 **CapsLock+** 的作者。**我就是我。**

**Comment by jiaoting** [comment]
不不，我的意思是，能否将左右上下集中在一个区域，这样方便小白联想记忆。目前的键位，我需要想半天才能记起来，当然练熟了无所谓，但是无形中增加了学习成本呐~~

在 2018-04-17 14:02:05，"Tom Zhu" <notifications@github.com> 写道：


@jiaoting 我安排的键位有着与 CapsLock+ 完全不同的排布逻辑。由于您已经用惯了 CapsLock+，不习惯我的键位是再正常不过的事。

另外，我是 Power Keys 的作者，不是 CapsLock+ 的作者。我就是我。

**Comment by szzhiyang** [comment]
@jiaoting 我能理解您的意思，然而我这个键位还真是经过我的深思熟虑的。

您稍加观察就可以发现，键盘上位于相同区域的键都对应着完全一致的方向键，相同手指所按的键的功能也是完全一致的，而且您亲自体验还会发现，像左移和右移、左选和右选等最常用的操作都是用最容易按下的键来完成的。而负责跳转行首行末、段首段末的按键在键盘上的位置与跳转到文章的位置都高度一致。另外我的键位还融入了 **加粗**、_斜体_、下划线、段落对齐等在富文本编辑中相当常用的格式操作。说真的，设计出这个键位是件相当令我自豪的事。 😄

**Comment by szzhiyang** [comment]
@qianjigit 

多番尝试后发现，改成右 `Alt` 键后，编辑文本的体验一落千丈，比老老实实地用方向键的体验还要差劲 😂 ，所以我只能先把 **Power Keys** 回滚到先前使用空格键时的状态了，不好意思。 🙏 

后续我会做个 GUI 来让用户开启或关闭 **Power Keys** 的各组功能。 

**不过不可否认的是，对于打字速度中下的用户而言，用空格键来编辑文本的体验是远远超越 CapsLock+ 的，但是我会再想想更加高明的解决方案的。**

**Comment by mengshj** [comment]
今天下载的版本，输入稍微快点就会跳了，例如输入命令 ps aux 经常跳到前面去

**Comment by szzhiyang** [comment]
@mengshj 

当然可以，我正在做 GUI。 😄 

感谢您的支持和鼓励。 🙏

**Comment by szzhiyang** [comment]
@qianjigit @jiaoting @mengshj 非常抱歉给大家添麻烦了，我已经将空格编辑的功能取消了。

**Comment by szzhiyang** [comment]
@qianjigit @jiaoting @mengshj 

我把空格编辑的功能砍掉了，因为它对打字的负面影响超过了正面影响。 👎 

但是，我仍然会探寻比 **VIM** 和 **CapsLock+** 更棒的解决方案的。 😄

**Comment by qianjigit** [comment]
我倒觉得不用砍掉，有个激活 / 取消的功能键就可以，就像 vim 的方式类似

**Comment by szzhiyang** [comment]
@qianjigit 可是如果这样的话，我倒还不如直接做个 **VIM** 键位呢。 😂

**Comment by jiaoting** [comment]
Good job!哈哈哈等不及下载了

**Comment by mengshj** [comment]
下载更新试试
