### ISSUE TITLE
Power Keys 导致电脑大写锁定逻辑反转，重启无效。

### ISSUE THREAD

**Issue by imjcroot** [szzhiyang/PerfectWindows#25]
打开大写锁定可以正常使用输入法输入汉字，关闭大写锁定才能输入大写字母。目前其他按键还未出现异常。

**Comment by jiaoting** [comment]
测试了一下，搜狗输入法没问题

**Comment by imjcroot** [comment]
我使用的就是搜狗输入法

**Comment by szzhiyang** [comment]
@imjcroot 非常感谢您的反馈，不过我重新审视了代码和库函数手册，发现我的代码没毛病啊。
