### ISSUE TITLE
提一些建议

### ISSUE THREAD

**Issue by Creeper233** [szzhiyang/PerfectWindows#26]
希望可以直接提供个目录放置Power-Keys.ahk，这样能方便用户根据自己的习惯的操作方式去修改快捷键
还有win+其他键操作时会弹出开始，这个能否取消，特别是调音量时，每按一遍弹一次挺难受的

**Comment by szzhiyang** [comment]
@Creeper233 

非常感谢您的建议和反馈。

**Power Keys** 主打也是最重要的特性就是最合理的快捷键预设，无需任何配置，开箱即用。由于每个预设快捷键都足够生动好记，且不跟任何现有的快捷键构成冲突，所以无需改键。如果您重新查看 **Power Keys** 的预设按键，您甚至会认为这些快捷键都是 Windows 原本自带的。

**Power Keys** 会导致开始菜单弹出的 bug 我还是头一次听说。就我目前掌握的信息来说，我不认为这是 **Power Keys** 的锅。为保险起见，您最好重新下载运行最新版 **Power Keys** ，谢谢。

**Comment by szzhiyang** [comment]
@Creeper233 

非常感谢您的理解，也非常感谢您向我提供如此宝贵的信息。

我初步认为您的电脑上存在另外的程序也在同时监控 Windows 徽标键，因而产生了冲突。由于目前我并不知道是谁正在与 **Power Keys** 发生冲突，所以我暂时难以解决这个问题。
