### ISSUE TITLE
我之前用了smart power plan，现在卸载了，还是关不掉节能模式

### ISSUE THREAD

**Issue by 244671360** [szzhiyang/PerfectWindows#28]

**Comment by szzhiyang** [comment]
似乎批处理文件在您的电脑上没有按照预期工作，麻烦您用注册表编辑器将 `HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Power` 键值清除，再重启电脑。

另外 Windows 系统设置也有管理节能模式的选项，如果您没有注意到，请留意一下这些选项。
