### ISSUE TITLE
游戏模式未按预期工作。

### ISSUE THREAD

**Issue by iGithunber** [szzhiyang/PerfectWindows#29]
进入游戏模式后在游戏中按空格键没反应，得退出软件才行。

**Comment by szzhiyang** [comment]
@iGithunber 

麻烦你退出并删除你正在使用的版本，并下载最新版本再试一下。

**Comment by szzhiyang** [comment]
@iGithunber 

开启游戏模式后空格键依旧无法使用是我的疏失，我现在已经解决了这个问题。烦请您退出并删除旧版，然后下载使用最新版。好消息是，最新版 **Power Keys** 已经可以自动更新了，所以这一次的麻烦将会成为历史。
