### ISSUE TITLE
重启，告知账号被停用。

### ISSUE THREAD

**Issue by Mcguffen** [szzhiyang/PerfectWindows#3]
我只能安全模式进入修改配置，重启。

**Comment by szzhiyang** [comment]
最新版本移除了相关操作。

如需恢复，请按住 Shift 键的同时重启电脑，进入带命令提示符的安全模式，并执行以下命令：

`net user Administrator /active:yes`

**Comment by pzhlkj6612** [comment]
老哥，要稳一点啊。你可以先判断下当前用户是不是Administrator（注意可能会被改名，所以得用另外的方法），再去决定是否禁用。

**Comment by szzhiyang** [comment]
这个纯属我考虑不周，非常抱歉。

**Comment by Mcguffen** [comment]
手动点赞，感谢您的开源奉献。

**Comment by szzhiyang** [comment]
感谢大家的包涵！
