### ISSUE TITLE
Windows 高级控制面板 使用出现问题

### ISSUE THREAD

**Issue by HaloWang** [szzhiyang/PerfectWindows#30]
这个软件不能先读取默认配置吗？我就开了一次，自带的独立显卡就不能用了，有什么恢复办法？也无法重装显卡的驱动了。哪些东西需要取消勾选？
![tim 20180502031351](https://user-images.githubusercontent.com/7344724/39489071-e0a44092-4db6-11e8-8074-c540ee74bd62.png)

**Comment by szzhiyang** [comment]
@HaloWang 

1. 这个软件每次启动时所展示的配置全是电脑当前的配置。

2. 我不清楚为什么独立显卡会失效。

**Comment by HaloWang** [comment]
依稀记得是取消勾选了实用功能中的小娜，OneDrive，时间轴，智能电源计划，然后重启电脑就出现了问题

使用 360 和系统自带的驱动更新程序都无法为 GTX1070m 安装驱动，只能使用 CPU 自带的集显

我已经通过 windows recovery 重置电脑了😅
