### ISSUE TITLE
打字的时候空格影响打字

### ISSUE THREAD

**Issue by Djcn** [szzhiyang/PerfectWindows#31]
如题

**Comment by szzhiyang** [comment]
@Djcn 

一开始做这个功能的时候，我没考虑周全。不过，现在我已经解决掉了这个问题，请退出并删除您现在使用的版本，然后重新下载最新版本试试，谢谢。

**Comment by followgiant** [comment]
在win10 cmder中无法使用空格

**Comment by szzhiyang** [comment]
@followgiant 

我这儿的 Cmder 一切安好啊。

您最好退出并删除旧版，再下载最新版的 **Power Keys** 试试。
