### ISSUE TITLE
功能建议

### ISSUE THREAD

**Issue by houxiren** [szzhiyang/PerfectWindows#32]
感谢您开发了如此好的软件。谢谢！！

1，可否实现在 exe 的同级目录下用 ini 文件实现设置的保存呢？
      这样的目的是实现便携。让软件的“免安装”可名符其实。
      也是为了让自定义更方便。
2，ini 文件能否支持相对路径？
      这样“便携”名符其实。这样我就能让 Power Keys 作为软件、文件、目录等一切一切的启动中心。
3，可否 ini 文件中可入选项可开关任务栏是否显示图标？

再次感谢开发如此好软！！！

**Comment by szzhiyang** [comment]
@houxiren 

非常感谢您的支持和鼓励，我的创意能得到认可真的是一件令我相当开心的事情。 😄 

之所以没有让那些快捷方式便携化是因为有相当多的快捷方式在脱离当前计算机后就会失效。

之所以没有在任务栏上显示图标是因为 **Power Keys** 的帮助页面、退出、重启以及游戏模式都有快捷键。

我没太看懂您的第二条建议，麻烦您能做出进一步的解释吗？

**Comment by houxiren** [comment]
谢谢您的回复！
第3条 不重要。能实现当然更好，这样我能把此软更好地推荐给公司的同事、朋友以及对电脑应用没那么熟但一样渴望高效的人群。对他们来说，有，会好很多。

第1条，您采用现在的结构不变，确实可以说“之所以没有让那些快捷方式便携化是因为有相当多的快捷方式在脱离当前计算机后就会失效。”
       关于此点的讨论，我认为应该将讨论角度放在：
1.1 您（或者说AHK）在技术上能否转变为用文件来保存设置？如果不行，就一切都无从谈起，讨论结束。
1.2 如果能，能否说出用文件来保存设置这种转变的好处，以使您愿意接受。

第1和第2条 是相辅相成的。缺了任何一条，威力都大打折扣。
我现在用的是 PStart，作为一切的启动中心。它采用程序同级目录下的同名 PStart.xml 文件来保存设置，便携，支持相对路径，自定义功能极强大。除了不能指定 F1 作为快捷键的首键，几近完美。

相对路径是指：
D:\Documents\Software\PStart.exe
D:\Documents\Software\TOOL\放大镜.exe
D:\Documents\Software\OFFICE\PDF\PDF转换.exe
D:\Documents\OFFICE\2018名单.xls
D:\VHD\VHD助手.exe
后4者在 PStart.xml 文件里面是这样记录的
Tools\放大镜.exe
OFFICE\PDF\PDF转换.exe
..\OFFICE\2018名单.xls
..\..\VHD\VHD助手.exe

**Comment by szzhiyang** [comment]
@houxiren 

谢谢您所提供的更多讯息，其实您只需称呼我为 “你” 就行了，我是晚辈。 😂 

看得出来，您所使用的绝大多数软件都是绿色软件，所以相对路径会显得相当好用，但是这显然不适用于那些需要安装才能使用的软件以及其他需要快速启动的项目。要知道，人们需要快速启动的东西是非常多样的，它们有些在系统盘，有些在其他盘；有些是命令行、有些是系统工具、有些是控制面板项，还有一些是网址。用配置文件和相对路径来管理拥有这么多路径和这么多类型的项目显然是不可行的。

另外，比起编辑配置文件和输入文件路径，创建和拖动快捷方式显然是更简单直观且对小白友好的方法。

**Power Keys** 一切的一切都是与快捷键相关的，所以任务栏图标会显得多余。

**Comment by houxiren** [comment]
我可否这样理解，您（AHK）在技术上能实现我的期盼，但您认为我的期盼不够好，所以暂不决定向这个方向走？

**Comment by szzhiyang** [comment]
@houxiren 

您的期盼用 AHK 都是能够做到的。不过我没有决定朝您所期盼的方向走的原因，并不是因为您的期盼不够好，而是因为我不希望大家在我的软件的配置上耗费太多时间，并且还有很多需要快速启动的项目无法以配置文件的方式记录。

举个例子，同样是用快捷键来快速启动您的 PDF 转换器，如果是用配置文件的话，您就需要手动将 PDF 转换器的完整路径或者相对路径输入到配置文件中；然而如果是用快捷方式的话，您只需要拷贝一份 PDF 转换器的快捷方式到 **Power Keys** 的快捷方式文件夹中就行了，并不需要您手动输入任何东西，省时省力。

再举个例子，同样是用快捷键来快速启动 `GitHub.com`，如果是用配置文件的话，您就需要手动将 `GitHub.com` 的网址输入到配置文件中；然而如果是用快捷方式的话，您只需要将 `GitHub.com` 从书签栏或者地址栏拖动到 **Power Keys** 的快捷方式文件夹中就行了，也不需要您手动输入任何东西，省时省力。

来自 Microsoft Store 的应用程序的路径是杂乱且难以定位的，而控制面板项以及 Windows 10 设置中心里的项目根本就没有路径的概念，它们根本无法以配置文件的形式来记录。

需要快速启动的很多项目单单记录文件路径是不全面的，因为它们还可能会有 “起始位置”、“启动参数” 、“窗口大小” 以及 “是否以管理员身份运行” 等信息需要指定。这么多的信息对于配置文件的编辑和管理可是个不小的挑战，然而快捷方式却能够以相当简单直观的方式妥善打理好这一切。

是时候拥抱新的方式方法了！ 😄

**Comment by houxiren** [comment]
不是拥抱新的方式方法的问题，而是囿于需打太多字的原因，无法向你充分地展示什么是更佳更全面。你的说法其实看似非常有道理，实则不然。如果您有空有兴趣的话，我发远程给你，并电话聊。

**Comment by szzhiyang** [comment]
@houxiren 

要不您以截图的形式告诉我您是如何配置 PStart 的吧，我想我应该可以从图中 get 到您的意思。 😄

**Comment by szzhiyang** [comment]
@houxiren 

PStart 没法添加来自 Microsoft Store 的应用程序啊，您是怎么解决的呢？

**Comment by szzhiyang** [comment]
@houxiren 

这就是 **Power Keys** 的一个功能啊，您真的没注意到吗？ 😂 

您不妨回顾一下 **Power Keys** 的 README 页面：

https://github.com/szzhiyang/PerfectWindows/blob/master/Power-Keys/Power-Keys.md

![1](https://user-images.githubusercontent.com/30952626/39633447-9cb7a4f6-4fea-11e8-8f93-1e040debb335.png)

**Comment by houxiren** [comment]
这就是 Power Keys 的一个功能啊，您真的没注意到吗？
要的不是3分熟的牛肉，而是想几分熟就几分熟。

**Comment by szzhiyang** [comment]
@houxiren 

那您真的应该开始学习 AutoHotkey 了，您不会后悔的，AutoHotkey 可以满足您的所有需求！

**Comment by houxiren** [comment]
这样吧，请教一下，有没有办法用参数的形式让 AutoHotkey运行 指定的脚本文件，比如：

AutoHotkeyU64.exe 快捷键.ahk

达到运行 AutoHotkeyU64.exe  目录下的 快捷键.ahk 的目的。

**Comment by szzhiyang** [comment]
@houxiren 

当然可以啦，不过我建议您使用 AHK 文件的绝对路径，而不是相对路径，因为相对路径只有在指定了正确的工作目录才会生效。

**Comment by szzhiyang** [comment]
@houxiren 

如果您需要配合 PStart 使用 AHK，最好将 AHK 脚本编译成 .exe 文件。

**Comment by szzhiyang** [comment]
@houxiren 

`Win + ?` 的快捷键被取消了，因为这个功能设计之初只是为了找个地方显示版本号以方便 bug 跟踪和软件的手动更新。但是 6.0 版本会在启动时显示版本号且会自动检查更新，所以 `Win + ?` 就显得多余了。

**Comment by houxiren** [comment]
谢谢您，一直没解决的问题，是灯下黑啊，原来AHK这么强大啊。其他的快捷键软件，也能自定义Win+这种系统自带（或叫系统占用）的快捷键，但自定义的优先级比系统的低，抢不过系统。
#f::
send #^+!P
return
就这么简单。谢谢您，启迪了我。

**Comment by houxiren** [comment]
我想了想，觉得在方向上讨论，没什么意义。因为无论哪种都是正确的。那不如折中一点，您在有时间、有心情的情况，考虑推一个支持ini设置文件，相对路径， Power Keys 本身的功能可选开关，可自定义的版本。这样兼顾小白与稍高阶一丁点的用户。

再次感谢！祝好！！

**Comment by szzhiyang** [comment]
@houxiren 

好的，肯定会的。

**Power Keys** 融入了我的诸多创新和摸索，它们需要经过一段时间的考验，这样我才能知道我的点子的价值和意义。

非常感谢您对我的支持和鼓励，如果您愿意的话，请您关闭该 issue，谢谢。

**Comment by houxiren** [comment]
好的。再次感谢。

**Comment by szzhiyang** [comment]
@houxiren 

祝您生活愉快，也祝 AutoHotkey 能给您带来更多快乐和便利。
