### ISSUE TITLE
游戏模式未按预期工作

### ISSUE THREAD

**Issue by cero-ss** [szzhiyang/PerfectWindows#33]
我平时绘画的时候，需要长按空格键拖动图层，就算开启游戏模式空格键依旧无法使用，需要关闭软件才行。不然这个软件对我来说就没用了。

**Comment by szzhiyang** [comment]
@cero-ss 

非常感谢您的反馈，开启游戏模式后空格键依旧无法使用是我的疏失，我现在已经解决了这个问题。烦请您退出并删除旧版，然后下载使用最新版。好消息是，最新版 **Power Keys** 已经可以自动更新了，所以这一次的麻烦将会成为历史。

**Comment by cero-ss** [comment]
新版本显示 Power Keys 的运行状态无法使用，虽然游戏模式打开后可以正常使用空格了，但是其它功能也随之关闭了，我在用ps画画的时候想换一首歌却不行，还是希望能有个主动关闭空格键功能的选项。必须重启才能关闭游戏模式也很麻烦，不够快。

**Comment by szzhiyang** [comment]
@cero-ss 

游戏模式不会影响切歌和音量调整功能的，切歌和音量调整功能可是打游戏中至关重要的的操作啊。 😂 

**Power Keys** 的冷启动是非常快的，所以即便是重启也是一眨眼的事。 😄

**Comment by szzhiyang** [comment]
@cero-ss 

看来问题已经得到了解决，我先关闭此 issue 了。
