### ISSUE TITLE
实在是忍无可忍！！！

### ISSUE THREAD

**Issue by Hansi7** [szzhiyang/PerfectWindows#35]
开源软件本来是好的。可是你这个不告知用户就填一堆一堆的自启动项是不是也太不厚道了。为了删除你这启动项，可费死劲了。看你源文件退出是有删除的注册表。但我明确说，不起作用！！！你自己用就算了。投稿到别处，再这样搞么多启动项，而且UAC开机就拦截，我找了两处注册表，删了以为没事了。结果进来就还是有UAC，实在是不厚道。

而且有时候还连续启动两次，就是啪啪出两次UAC问我是否启动，是不是神经病啊，真心想骂人了。
真的。
你要是代码没调好，不是故意的就算了。你要是故意的，这人品真是没救了。
自启动不告知，真的好吗？流氓软件都有这个选项了，实在不行你弄个卸载脚本吧。服了！！！

另外，60%键盘用不了，能用也不用了。自定义别的脚本了。

**Comment by szzhiyang** [comment]
@Hansi7 

你明明都从源码中看出来软件退出时会删除自启条目，为什么还要指责我？删除注册表不成功，难道还怪我？你有没有考虑一下你杀毒软件的问题？需要的时候就用，不需要的时候就退出，什么注册表残余都不会留下。

我问心无愧。

**Comment by szzhiyang** [comment]
@Hansi7 

但是这是用 AutoHotkey 脚本写的，RegDelete 语句完全就是按照它的语法要求写的。如果脚本没有按照预期执行，我也不知道怎么办啊。

**Comment by szzhiyang** [comment]
@Hansi7 

我的想法很简单，就是如果这个软件关机时还在运行，那就说明用户比较依赖这个软件，所以它就会在下次开机时自启；而如果这个软件被用户手动退出了，那就说明用户并不会长期使用这个软件，所以它就会在退出时删除自启项。这样用户不需要进行什么额外操作，软件就能按照他们的意愿自启或者不自启，我觉得没毛病啊。

**Comment by Hansi7** [comment]
写个卸载脚本么？
我给出问题都附带了解决方法。真的很良心了。
可启动项写多个地方，这是出于什么考虑的？

**Comment by szzhiyang** [comment]
@Hansi7 

这个软件对系统所做出的唯一两处更改就是：

1. 自启项
2. 像其他软件一样在 `%LocalAppData%` 存放用户数据

所以卸载脚本是不必要的。

两个自启项一个是常规自启，一个是组策略自启。组策略自启稳定性会更好，因为常规自启会因某个组策略配置失效，两者一起使用相当于是双保险。

这个软件只允许单实例运行，所以当这个软件重复启动时，后来的实例会自动退出。所以，弹两次 UAC 是非常罕见的情况。

**Comment by szzhiyang** [comment]
@Hansi7 

不过刚才想了想，写两个自启项似乎没有什么必要，因为那个会影响自启的组策略也不太可能会出现在用户电脑上，我等一下把软件改改。

**Comment by szzhiyang** [comment]
@Hansi7 

以前玩组策略比较多，看来我有点小心过头了。 😂

**Comment by szzhiyang** [comment]
@Hansi7 

我刚才已经把自启项缩减为一个，弹两次 UAC 的事应该不会再发生了。

你还提到 60% 的键盘不能用，能具体描述一下吗？

**Comment by szzhiyang** [comment]
@Hansi7 

你好，这是 **Power Keys** 下个版本的样子，欢迎你随时回来。 😄 

![demo](https://user-images.githubusercontent.com/30952626/39958006-c844fd86-562e-11e8-9788-cf07ad184f6d.png)
