### ISSUE TITLE
与 QQ 密码框存在兼容性问题。

### ISSUE THREAD

**Issue by SiaYung** [szzhiyang/PerfectWindows#36]
现有软件版本   7.0.1；
存在问题：开启软件的情况下，登录QQ输入密码总是提示密码错误，关闭软件后正常。（确定密码正确输入，密码存在大小写。输入过程中通过Capslock键切换大小写）

**Comment by szzhiyang** [comment]
@SiaYung 

感谢反馈，我已经着手调查这个问题，查清原因后我会回复你的。

**Comment by SiaYung** [comment]
谢谢！！！

**Comment by szzhiyang** [comment]
@SiaYung 

初步判断应该是 QQ 的安全措施将 **Power Keys** 识别为盗号木马并将 **Power Keys** 屏蔽了。

**Power Keys** 之所以能够使用大量前缀不为 `Ctrl` 、`Shift`、`Alt` 或者 `Win` 的快捷键，就是因为它使用了键盘钩子并持续监听键盘活动。不过，这种技术在为大家提供便利的同时，也经常被盗号木马所恶意利用，所以被 QQ 密码输入界面屏蔽是很正常的现象。其实，我本人也很支持 QQ 的这种做法，毕竟在便利与安全不可兼得时，安全是最重要的。

所以，解决方法只有两种：

1. 让 QQ 记住密码
2. 输入 QQ 密码时退出 **Power Keys**

**Comment by szzhiyang** [comment]
@SiaYung 

我想我已经向您解释清楚了这个问题，所以我关闭了此 issue。不过，您仍然可以继续在下方 comment 。 😄

**Comment by SiaYung** [comment]
也只能这样了
