### ISSUE TITLE
如何长按空格键？

### ISSUE THREAD

**Issue by 130536419** [szzhiyang/PerfectWindows#37]
管理你好。PS的抓手工具要长按空格键。但是我又不能退掉 Power-Keys，因为用PS过程中要经常开文件夹。 我找了下，有进入游戏模式，和重启软件。  用这个切换  PS和开其他程序或文件夹  2次的操作间隔时间长还是没有问题的。如果来来回回开文件夹和程序，又要去用PS抓手。这样用游戏模式的按键，就有点繁琐了。

是不是有设置取消空格按键的快捷键的地方。是不是我没有找到。

**Comment by szzhiyang** [comment]
@130536419 

按住空格键的同时再按住 `Shift` 就可以使用抓手工具了。😀

**Comment by szzhiyang** [comment]
@130536419 

我正在着手为 **Power Keys** 添加更精细的选项以方便大家更加自由地控制 **Power Keys** 的功能的开启与关闭，敬请期待。 😄

**Comment by 130536419** [comment]
期待...

**Comment by szzhiyang** [comment]
@130536419 

您好，新版 **Power Keys** 已经完工（目前正在测试），您将能够从任务栏托盘轻松访问您所关心的选项。

由于本 issue 所涉及到的问题很快就会被消除，所以我关闭了此 issue。不过，您仍然可以在下方继续 comment 。

![demo](https://user-images.githubusercontent.com/30952626/39957910-57d8dc3a-562d-11e8-8724-a8b830e4c05a.png)
