### ISSUE TITLE
数字小键盘兼容性问题

### ISSUE THREAD

**Issue by Aquarian-Age** [szzhiyang/PerfectWindows#39]
如题 启动软件后默认启用了小键盘无法使用快捷键取消掉 需要重新注销才可以返回正常键盘 一旦软件启动就是会自动启动小键盘 没办法打字。。。。

**Comment by szzhiyang** [comment]
@Aquarian-Age 

天哪！不好意思，我竟然忘记了有些笔记本电脑上自带了数字小键盘，抱歉抱歉，我马上改！ 😂

**Comment by szzhiyang** [comment]
@Aquarian-Age 

您好，请删除您目前使用的版本并下载使用最新版本的 **Power Keys**，版本为 8.0.4，该版本解决掉了这个问题。 😄 

如果问题仍然存在，请重新打开该 issue，谢谢您！

**Comment by 130536419** [comment]
@szzhiyang 8.0.4    台式键盘  按字母上的数字 1,2  会自动关闭  右侧数字区的  numlock数字锁定键    ``

**Comment by szzhiyang** [comment]
@130536419 

感谢反馈，我马上会做出选项让这个功能单独启用或禁用，请稍候。

**Comment by szzhiyang** [comment]
@130536419 

请重启 **Power Keys**，片刻后 **Power Keys** 就会自动更新至 8.0.5 版本，该版本解决了您所提到的问题。
