### ISSUE TITLE
Windows 8.1 Alt + Tab 兼容性问题

### ISSUE THREAD

**Issue by mssalike** [szzhiyang/PerfectWindows#40]
这个问题我重启了好几次，希望可以解决这个兼容问题。是不是必须win10？

**Comment by mssalike** [comment]
虚拟机测试了一下win10可以。没有兼容问题

**Comment by szzhiyang** [comment]
@mssalike 

您好，非常感谢您的反馈。我刚才对代码做了微调，问题应该能够解决。请重启 **Power Keys**，它将会自动更新至 8.1.1 版本。您也可以从 **Power Keys** 的帮助文档处下载最新版本。

如果问题已解决，请您关闭该 issue，否则请继续留言，谢谢。

**Comment by szzhiyang** [comment]
@mssalike 

似乎您所提到的问题已经得到了解决，我先关闭此 issue。您仍然可以在有必要时重新打开此 issue。
