### ISSUE TITLE
泰语输入法兼容性问题

### ISSUE THREAD

**Issue by sky31even** [szzhiyang/PerfectWindows#41]
New surface pro，最新win10系统，装的64位exe。

切换到泰语输入法的时候，会遇到无限弹窗，内容就是提示powerkeys在当前键盘布局下不可用，我知道不可用，但是也没必要无限弹窗把= =每次都需要任务管理器直接关闭并退出整个程序，望改进。

**Comment by szzhiyang** [comment]
@sky31even 

我从来都没有编写过这样的弹窗，能截个图给我看看吗？

**Comment by szzhiyang** [comment]
@sky31even 

似乎您并没有帮助改进 **Power Keys** 的意思，那我只好关闭该 issue 了，有需要时请重新打开它。

**Comment by sky31even** [comment]
![image](https://user-images.githubusercontent.com/18375514/40547785-02e4aa94-605d-11e8-9c1a-46287766d08b.png)

如图

**Comment by szzhiyang** [comment]
@sky31even 

抱歉，这个问题我恐怕是解决不了了，因为如果要为各种小语种键盘布局做单独优化的话，工作量太庞大了。 😱

**Comment by szzhiyang** [comment]
@sky31even 

我尝试在 Google 和 AutoHotkey 的帮助手册查找去除那个窗口的办法，却没有任何结果，实在非常抱歉。

**Comment by szzhiyang** [comment]
@sky31even 

另外，我强烈建议您退出并删除当前的版本，并前往 https://github.com/szzhiyang/PerfectWindows/wiki/Power-Keys 下载最新版本使用，非常感谢。
