### ISSUE TITLE
前辈，您好。我又来了，请教您问题。

### ISSUE THREAD

**Issue by houxiren** [szzhiyang/PerfectWindows#42]
前辈，好。
向您请教问题，不是关于 Power Keys 的，期盼您能帮忙回答。

1，输入 F1 + 1 达到输入 Ctrl +Shift + Alt + Q 代码可以用下面的。如果输入F1 + 1 + 2 代码要怎么写？
F1 & 1::
send ^+!Q
return

2，有没有办法用AHK实现，我自己在AHK文件中写入我自己的QQ号码和密码，以实现自动填写和登陆？

上次和您聊了后，获益良多。再次感谢您！祝好！

**Comment by szzhiyang** [comment]
@houxiren 

您好，以下是 AutoHotkey 官方帮助手册的原文，它可以解决您有关三键快捷键的疑问：

> Combinations of three or more keys are not supported. Combinations which your keyboard hardware supports can usually be detected by using #If and GetKeyState, but the results may be inconsistent. For example:

```autohotkey

; Press AppsKey and Alt in any order, then slash (/).
#if GetKeyState("AppsKey", "P")
Alt & /::MsgBox Hotkey activated.

; If the keys are swapped, Alt must be pressed first (use one at a time):
#if GetKeyState("Alt", "P")
AppsKey & /::MsgBox Hotkey activated.

; [ & ] & \::
#if GetKeyState("[") && GetKeyState("]")
\::MsgBox

```

如需快速输入账号密码，请参阅官方帮助手册的 `Hotstrings and Auto-replace` 和 `SendInput` 章节。

---

我学习 AutoHotkey 基本上只看它自带的帮助手册，因为这个帮助手册写地相当用心，举例也非常丰富，几乎涵盖了我们所能想到的所有操作。

然而，我不建议使用三键快捷键，因为三键快捷键要比双键快捷键难按得多。这也是我为 **Power Keys** 中加入 **简化快捷键** 功能的原因。

---

为了保护我们的私人交流，我关闭了此 issue 以掩人耳目。 😂  这并不妨碍我们后面的交流。

**Comment by houxiren** [comment]
感谢前辈,第1个问题,完美解决.

第2个问题有解吗?

**Comment by szzhiyang** [comment]
@houxiren 

我回答了第二个问题了啊。 😂 

---

如需快速输入账号密码，请参阅官方帮助手册的 `Hotstrings and Auto-replace` 和 `SendInput` 章节。

**Comment by houxiren** [comment]
我资质愚钝,手头有中文版的帮助还是不会.能否直接给出代码?要求多多,实在是不好意思.

刚才碰到了个问题,
F1 & 1::
send ^+!Q
return
这样有效。

但下面这个就无效，不知道是什么原因
F1 & 2::
send 感谢您！
return

**Comment by szzhiyang** [comment]
@houxiren 

可是您所写的代码没有任何问题啊，奇怪。

**Comment by houxiren** [comment]
我自己换个环境再试一下。
QQ自动登陆，期盼您的帮忙。

**Comment by houxiren** [comment]
QQ自动登陆，在网上找到了。谢谢您。

另外
F1 & 2::
send 感谢您！
return

无效。找到原因了，是这行的上方有

#if GetKeyState("[") && GetKeyState("]")
\::MsgBox，感谢您！
return

不知道有没有办法，#if GetKeyState……有效，又不影响它下方的代码的有效性。

**Comment by houxiren** [comment]
谢谢您！再加上个 #if 就可以了。——有效。

有个新问题，以下代码，按住 [ ] \ 然后同时松开，可以实现弹出窗口别客气！
但会在编辑处留下 [ ] 这两个符号，有没有办法不要留下？

#if GetKeyState("[") && GetKeyState("]")
\::MsgBox, 别客气！
return
#if
