### ISSUE TITLE
I download this script source, but run across an error.

### ISSUE THREAD

**Issue by TYZRPVX** [szzhiyang/PerfectWindows#43]
It looks like this:
![image](https://user-images.githubusercontent.com/7645818/40585246-ed8212a0-61e1-11e8-8eaa-ab83b226a41b.png)

**Comment by szzhiyang** [comment]
@TYZRPVX 

Hello, I think you might mistakenly downloaded a wrong version of the source code, because the redundant asterisks have been removed a long time ago.

<br>

![1](https://user-images.githubusercontent.com/30952626/40620555-cc178d58-62cb-11e8-85c0-c9e6e268cbd6.png)

**Comment by TYZRPVX** [comment]
Maybe this is not the real reason.

This is the script looks like:
![image](https://user-images.githubusercontent.com/7645818/40634998-7b677d6e-632a-11e8-9f53-3ff6f4fab458.png)

asterisks is not contained. Maybe some versions of AHK had remove the asterisks grammar. 

Can you run the script successfully? Can you show the version of your AHK version.

**Comment by szzhiyang** [comment]
@TYZRPVX 

Of course, the scripts run perfectly on my PC. I am using `v 1.1.28.02`.
