### ISSUE TITLE
[Proposal] 启动快捷方式时继承当前工作目录

### ISSUE THREAD

**Issue by zjuchenyuan** [szzhiyang/PerfectWindows#44]
我时常需要在资源管理器当前目录地址栏输入bash或cmd来启动命令行窗口

快捷方式`起始位置`设置为空，启动程序的工作目录就会是当前目录（而不是System32）

现在尝试了将`起始位置`设置为空的快捷方式放入Power Keys文件夹中，启动的bash还是System32目录，导致不可用

请求考虑支持这种提取当前目录并继承给启动的程序的特性

**Comment by szzhiyang** [comment]
@zjuchenyuan 

我一直也很想做到这一点，不过我实在做不到，因为这件事似乎只能用 Shell 扩展来实现，但是我现在的水平还不足以写 Shell 扩展。

不过有一点是肯定的：一旦我学会如何实现这个功能，我会在第一时间加上去的。
