### ISSUE TITLE
大小写（Caps Lock）出现延迟问题

### ISSUE THREAD

**Issue by makejavas** [szzhiyang/PerfectWindows#45]
快速打英文时切换大小写的时候出现延迟。
经常打出多个大写字母。
如快速输入Start
会变成STart
码字慢不影响。
关闭软件后正常。

**Comment by szzhiyang** [comment]
@makejavas

你好，就像许多其他键盘效率工具一样，**Power Keys** 在大写锁定键上也做了许多文章。因此，只有当松开大写锁定键时，字母大小写才会切换。

不过，之所以你会困扰于该问题，是因为你打字方式不规范。

按照打字的规范，只有在 **连续输入许多大写字母时** 才应使用大写锁定键。输入单个或少量大写字母的标准做法（也是最快做法）是： **按住 Shift 键的同时再按下字母键**。
