### ISSUE TITLE
调整音量的快捷键没有按照预期工作。

### ISSUE THREAD

**Issue by CoderGrowing** [szzhiyang/PerfectWindows#46]
笔记本（华硕R557L）自带了媒体音量键的功能，音量增大键为Fn+F12。
开启PowerKeys后使用数字键区的加等号键却变成了增大音量的功能。

**Comment by szzhiyang** [comment]
@CoderGrowing 

似乎 **Power Keys** 在您的电脑上没有按照预期工作，请按几下 Windows 徽标键，看看问题是否仍然存在？

**Comment by szzhiyang** [comment]
@CoderGrowing 

由于您长期未回复，该 issue 已关闭，不过您仍然随时都可以重新打开它。
