### ISSUE TITLE
“选定文本”组合按键没有用

### ISSUE THREAD

**Issue by JunHong1995** [szzhiyang/PerfectWindows#48]
操作系统信息如下所示：

![image](https://user-images.githubusercontent.com/31408456/41265392-a4681e12-6e24-11e8-9eac-ad28d9af1657.png)

无论是“空格+A”还是“空格+;”都不行

**Comment by szzhiyang** [comment]
@JunHong1995 

您好，我觉得您可能误会了选定文本的做法了。

举个例子，如果您想向左选定一个词语，则要先按住空格键，再按住 `;` 键，在前两个键不松开的情况下按 `d` 键。

另外，我刚才大幅度地改进了空格编辑功能的易用性，建议您通过 **Power Keys** 的任务栏菜单将其更新至最新版本 `8.4.1`，谢谢。
