### ISSUE TITLE
与 VMware 12 发生冲突

### ISSUE THREAD

**Issue by FrankSFLYS** [szzhiyang/PerfectWindows#49]
开启 PowerKeys 时使用 VMware 虚拟机会导致虚拟机的 Capslock 无法正常唤醒或一直闪烁。估计是因为同时使用键盘钩子导致的冲突。

**Comment by szzhiyang** [comment]
@FrankSFLYS 

您好，我这边不曾出现过这一问题。

我的 VMware 版本是 `14.0.0` ，虚拟机内的操作系统是 Windows 7 最新版本，请问您的版本是什么？

**Comment by FrankSFLYS** [comment]
我的是 VMware workstation Pro 12.0.0

**Comment by szzhiyang** [comment]
@FrankSFLYS 

要不您试试开启 **Power Keys** 的游戏模式？

**Comment by FrankSFLYS** [comment]
嗯，开启游戏模式好了。如果我想自己改改脚本，实现开启某些应用自动开启游戏模式，请问游戏模式在哪个文件中开启呢？

**Comment by szzhiyang** [comment]
@FrankSFLYS 

您可以在 `Libs/TrayMenu.ahk` 中找到切换游戏模式的相关代码。 😄

**Comment by FrankSFLYS** [comment]
好的，谢谢啦

**Comment by szzhiyang** [comment]
@FrankSFLYS 

别客气哦。 😄
