### ISSUE TITLE
有关 UI 的探讨

### ISSUE THREAD

**Issue by guzzhao** [szzhiyang/PerfectWindows#50]
启动的时候不需要这么大的字,
"更新 power keys" 怎么和重启一样.弄成和其他软件更新一样就行.

**Comment by szzhiyang** [comment]
@guzzhao 

我在 UI 方面不是很擅长，您可以帮我设计一个更好的。 😄 

之所以以这种方式更新 **Power Keys**，主要是因为我不知道如何中断文件下载。
