### ISSUE TITLE
关于自动创建目录的想法

### ISSUE THREAD

**Issue by jed-z** [szzhiyang/PerfectWindows#51]
软件似乎会自动创建 C:\Program Files\szzhiyang\Power Keys 目录，涉及更新等操作相关的文件（如 Power-Keys-Updater.exe 等）好像也都会在这个目录下进行。但事实上我更习惯将这些对硬盘读写较小的软件放在 D 盘下，也不希望绿色软件利用管理员权限在 C:\Program Files 下做修改。能否使其均进行在软件本体目录内？

**Comment by szzhiyang** [comment]
@jed-z 

您好，之所以在 **`%ProgramFiles%`** 中写入更新程序，是因为在不久之后，**Power Keys** 将变成一个需要安装在 **`%ProgramFiles%`** 的软件，而不再是一款绿色软件。

**Power Keys** 之所以最终将变成一款需要安装的软件，是因为一个后台常驻且以单线程运行的绿色软件难以做到或者无法做到以下事情：

1. 在不弹 UAC 的情况下以管理员身份启动，就像杀毒软件一样
2. 定期自动检查更新，并在合适的情况下提醒并实现自我更新，就像 **Microsoft Office** 一样
3. 清理其配置文件、注册表项和计划任务项
4. 管理开始菜单、桌面和任务栏的快捷方式
5. 减轻用户手动管理配置文件、手动清理冗余项目以及手动更新软件的负担

总之，一切的一切都是在为 **Power Keys** 更好的使用体验铺路。一款软件只有在拥有完整的安装、修复和卸载流程的情况下，才能将用户体验做到最好。

**Comment by jed-z** [comment]
感谢你的说明。当前情况下，开机自启弹出 UAC 确实有点不爽。
如果要成为一款安装软件，仍希望可以将安装目录的决定权交由用户，亦或考虑诸如%appdata%的目录（个人浅见）

**Comment by szzhiyang** [comment]
@jed-z 

由于 **`%AppData%`** 已经被用来存放用户配置的快捷方式，**Power Keys** 将只能安装在 **`%ProgramFiles%`** 中。
