### ISSUE TITLE
有关更新功能的建议

### ISSUE THREAD

**Issue by jed-z** [szzhiyang/PerfectWindows#52]
对我来说，在较差的网络环境下，当前版本（8.5.0） Power Keys 的更新功能体验很差。主要体现在两个方面：
1. **不能检测当前是否为最新版本**。应该先从远程获取最新版本号进行判断。目前情况是，即便是最新版本仍然会重新下载。
2. **不能显示升级进度**。今天不知道为何网络不好，下载速度不超过 20K/s。体现在 Power Keys 中，就是红底白字一直显示在屏幕中间，而且貌似还是最顶层，**没有停止按钮，也不能最小化或隐藏**，只能结束进程。

**Comment by szzhiyang** [comment]
@jed-z 

1. 我没有自己的服务器，所以现在 **Power Keys** 的下载和更新都必须在 **GitHub** 的服务器上进行。在拥有更快更稳定的服务器前，我没有解决办法。
2. 我不知道如何在 **AutoHotkey** 中获取下载进度、中断或者继续下载进程。
3. **我需要协助。**

**Comment by jed-z** [comment]
关于 AHK 获取下载进度方面我可能无法提供更多帮助，因为我完全不熟悉它的使用方法。服务器的话可以考虑国内的云主机，它们对学生都有较可观的优惠。或者，因为我有一台腾讯云服务器，如果你愿意而且不嫌弃的话，可以暂时提供给你用来实现检查版本、文件下载功能。有意可私聊。

**Comment by szzhiyang** [comment]
@jed-z 

非常感谢您的理解和支持！
