### ISSUE TITLE
如何使用空格编辑功能选定文本？

### ISSUE THREAD

**Issue by tchy** [szzhiyang/PerfectWindows#53]

**Comment by szzhiyang** [comment]
@tchy 

您好，恕我没能将选定文本的做法描述到位，我已经修改了选定文本的做法的描述语句，希望能帮到您：

![demo](https://user-images.githubusercontent.com/30952626/41539567-a5336682-7340-11e8-9688-3db41fc36c0a.png)

**Comment by szzhiyang** [comment]
@tchy 

您好，由于该 issue 所涉及的内容已合并至 **Power Keys** 的帮助文档中，故该 issue 已被关闭，感谢您的理解与支持。
