### ISSUE TITLE
空格编辑【SPACE+F1】没有提示

### ISSUE THREAD

**Issue by loseloner** [szzhiyang/PerfectWindows#56]
知阳： 你好！

按住空格键，再按 F1 键即可显示上表 ==》 不能实现，会启动帮助网页;
请修正！

**Comment by szzhiyang** [comment]
@loseloner 

您好，请将 **Power Keys** 更新至 `8.5.1`，该帮助功能是在 `8.5.0` 版本引入的。

**Comment by loseloner** [comment]
8.3.8 自动更新失败，我还以为没有更新。因为，GitHub也没更新日志看;
说来奇怪，别人写软件都有日志,为什么你没有加？ 建议在显著位置加上吧，方便用户追踪

**Comment by szzhiyang** [comment]
@loseloner 

好的，我会加上更新日志的，请问您现在有成功将其更新吗？

**Comment by loseloner** [comment]
铁粉当然第一时间更新！

**Comment by szzhiyang** [comment]
@loseloner 

很抱歉给您带来不便，如果您发现了其他问题或者有新功能要求，请尽管告诉我。
