### ISSUE TITLE
win10无法实现开机自动启动

### ISSUE THREAD

**Issue by Aquarian-Age** [szzhiyang/PerfectWindows#57]
win10最新版本1803 无法实现开机自动启动
软件下载在E盘里面某个目录里  勾选了开机自启
我把他连接到了"开始屏幕"

每次启动都要显示系统的"用户账户"控制选项才会启动
不知道是不是这个原因

**Comment by Aquarian-Age** [comment]
谢谢

获取 Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by szzhiyang** [comment]
@Aquarian-Age 

如果您后来成功让 **Power Keys** 开机自启，麻烦您关闭此 issue，否则请告诉我提供更多信息，谢谢！

**Comment by szzhiyang** [comment]
@Aquarian-Age 很抱歉给您带来不便。

**Comment by Aquarian-Age** [comment]
已关闭 软件很好用 我自己禁用了启动项 没注意 抱歉了

获取 Outlook for Android<https://aka.ms/ghei36>



发件人: Tom Zhu
发送时间: 7月7日星期六 下午6:16
主题: Re: [szzhiyang/PerfectWindows] win10无法实现开机自动启动 (#57)
收件人: szzhiyang/PerfectWindows
抄送: Aquarian-Age, Mention


@Aquarian-Age<https://github.com/Aquarian-Age> 很抱歉给您带来不便。
―
