### ISSUE TITLE
修改空格编辑按键绑定

### ISSUE THREAD

**Issue by happytommyl** [szzhiyang/PerfectWindows#58]
你好，请问能否修改空格编辑模式的Key-mapping呢？我比较习惯vim的按键布局，重新习惯Powerkey的布局有些麻烦了。但是你的作品的其他功能还是很好用的，也很难找到其他的代替品，谢谢

**Comment by szzhiyang** [comment]
@happytommyl 

**非常感谢您的支持和鼓励！**

**Power Keys** 后面肯定会实现键位自定义功能的，可是由于当前的空格编辑功能的设计理念和实现逻辑与 Vim 的有着很大的不同，所以这个功能暂时难以在短期内实现，但我仍会尽我最大努力。

**我想知道：**

* 您是从哪里得知 **Power Keys** 的？
* 您中意它的哪个 / 哪几个功能呢？
* 您期待哪些新功能？
