### ISSUE TITLE
希望能够自定义键位！

### ISSUE THREAD

**Issue by LarenDorr** [szzhiyang/PerfectWindows#59]
用了一下，很好用，如果能够自定义的话更好了。
有个疑问：
我原先自己写过一个很简单按键映射，用来映射ctrl+[ or ] 为切换左右虚拟桌面
```
<^[::^#Left
<^]::^#Right
```
可是当桌面移到某些应用上时，例如cmder，按键映射就失效了。
为什么你的
```
Tab & LWin::^#Left
Tab & LAlt::^#Right
```
就可以完美使用。求解

**Comment by szzhiyang** [comment]
@LarenDorr 

**感谢您的支持和鼓励！**

方便具体说说您希望自定义哪些功能吗？

**Comment by LarenDorr** [comment]
@szzhiyang  我说的自定义是指对键位的自定义，固定的键位总觉得别扭，毕竟人的习惯不同。
如果能够把键位设置用config文件或者其他易于更改的方式暴露出来，就很舒服了。
我试了用管理员身份运行，完美解决问题，非常感谢！

**Comment by szzhiyang** [comment]
@LarenDorr 

别客气，问题解决了就好。 😄 

您指的是「空格编辑」功能的键位对吧？**Power Keys** 的好几个功能都有键位的概念。 😂 

**如果您是 Vim 或  Emacs 用户：**

> 那么您短期之内可能无法将「空格编辑」功能自定义成您所习惯的状态，因为「空格编辑」的设计理念和实现逻辑与 **Vim** 和 **Emacs** 有很大的不同。

**如果您不是 Vim 或  Emacs 用户：**

> 请分享一下经您自定义后的大致键位，这样我将能更容易地构思和实现键位自定义功能，谢谢！
