### ISSUE TITLE
最新8.8.5版本，在给文件或文件夹改名的时候无法使用空格，需要按win＋esc键切换到游戏模式才可以

### ISSUE THREAD

**Issue by qikid** [szzhiyang/PerfectWindows#65]
最新8.8.5版本，在给文件或文件夹改名的时候无法使用空格，需要按win＋esc键切换到游戏模式才可以

**Comment by szzhiyang** [comment]
@qikid 

我这儿没有这个问题啊，请问您用的是什么输入法？有运行其他键盘脚本类工具吗？

**Comment by szzhiyang** [comment]
@qikid 由于您长时间不回复，此 issue 已关闭，如有需要请重新打开该 issue。
