### ISSUE TITLE
希望能为各个功能提供独立的开关

### ISSUE THREAD

**Issue by Night8848** [szzhiyang/PerfectWindows#66]
F1~F12的快捷启动十分好用，但是"简化快捷键"功能较为严重的影响了我的使用体验，很多需要用到Esc 和 `的时候无法发挥原有的作用，也不能设置成其他软件快捷键的一部分，希望能够添加单独的开关按需选用。

**Comment by szzhiyang** [comment]
@Night8848 

您好，感谢您的反馈和建议。

按照设计的预期，简化快捷键功能是不会对 `Esc`、`~`、`Tab`、`Caps Lock` 以及 `Shift + Esc`、`Alt + Esc`、`Win + Esc`、`Ctrl + Esc`、`Ctrl + Shift + Esc`、`Ctrl + Tab`、`Ctrl + Shift + Tab`、`Alt + Tab`、`Shift + Tab`、`Shift + ~`、`Alt + ~`、`Ctrl + ~` 等等快捷键的原本功能构成任何影响的。从您的表述来看，似乎有软件不兼容 Power Keys 的按键发送方式，方便告诉我有哪些软件出现了这样的问题吗？这样我好排查和解决问题。

**Comment by Night8848** [comment]
当时是运行游戏 DNF ，在游戏中无法使用Esc键原有的功能，再就是（应该是Rolan中，不太确定）试图用Alt+~作为快捷键时无法设定成功，关闭power keys才设定好。
  感谢您的及时回复。

**Comment by szzhiyang** [comment]
@Night8848 

游戏对按键的检测一般都是比较复杂的，所以 Power Keys 自带了 **游戏模式**。您可以在打游戏前启用游戏模式，这样简化快捷键的功能会暂时禁用，也就不会出现这样的问题了。

稍后我会改写简化快捷键功能的代码，改写完成后应该就不会有 Rolan 那样的兼容性问题了，届时我会通知您的。

**Comment by Night8848** [comment]
我之前是通过游戏模式来解决这个问题，但是游戏本身的按键是和F1~F12快捷启动没有任何冲突的，比如说我自己，这种非全屏游戏时候会用快捷键启动播放器，或者打开Eagle、Tim截图保存或者分享什么的，希望游戏模式能够保留快捷启动功能。

**Comment by szzhiyang** [comment]
@Night8848 

在我玩的游戏中，长按 `F2` 和短按 `F2` 的功能是不一样的，所以快捷启动和游戏模式不可兼得。

**Comment by szzhiyang** [comment]
@Night8848 

我已经更新了 Power Keys，看看您遇到的兼容性问题是否得到解决？

**Comment by Night8848** [comment]
是简化快捷键的兼容性吗？我晚上才有空，到时候给您回复。

**Comment by szzhiyang** [comment]
@Night8848 

是的，您什么时候回复我都可以。

**Comment by Night8848** [comment]
简化快捷键在Rolan中已经可以正常工作

**Comment by szzhiyang** [comment]
@Night8848 

非常感谢您帮忙测试，如果您后续仍遇到了任何问题或是有任何希望添加的功能，请您尽管提出！ 😄

**Comment by szzhiyang** [comment]
@lfk0 

我从来都没停止过对 **Power Keys** 的各个缺陷的修复，毕竟我自己也非常依赖 **Power Keys**，方便说说是在输入什么词语的时候会多出数字 1 吗？

**Comment by szzhiyang** [comment]
@lfk0 

最新版本的 **Power Keys** 还有您遇到的这个问题吗？

**Comment by lfk0** [comment]
> @lfk0
> 
> 我从来都没停止过对 **Power Keys** 的各个缺陷的修复，毕竟我自己也非常依赖 **Power Keys**，方便说说是在输入什么词语的时候会多出数字 1 吗？

随机出现的，小狼毫、win10自带 都会出现这个功能，似乎是在我按了1进行选词之后，马上又跟着插入了一个1

**Comment by szzhiyang** [comment]
@lfk0 

很抱歉给您带来不便。

我自己用的也是 Windows 10 自带的输入法，不过尚未遇到过这个问题。

麻烦您使用最新版本 **Power Keys** 一段时间，看看还能不能遇到这个问题，非常感谢。

**Comment by lfk0** [comment]
最新版也有问题，每天能发生几十次，所以每周更新一次，期盼着修复此bug……

**Comment by szzhiyang** [comment]
@lfk0 

我刚才又在学校机房的好几台电脑上测试（Windows 10 输入法和搜狗输入法都有测试），还是暴露不出问题，您有将 **Power Keys** 加到杀毒软件的白名单里吗？

**Comment by szzhiyang** [comment]
@lfk0 

原来是这样啊。 😂 

那您以后在虚拟机中打字时，把宿主机的 **Power Keys** 的游戏模式打开，然后在虚拟机里面跑 **Power Keys** 就行了。

如果您往后在宿主机上遇到了 **Power Keys** 的其他问题，请尽管提出，我们一起找原因。 😄

**Comment by lfk0** [comment]
> @lfk0
> 
> 原来是这样啊。 😂
> 
> 那您以后在虚拟机中打字时，把宿主机的 **Power Keys** 的游戏模式打开，然后在虚拟机里面跑 **Power Keys** 就行了。
> 
> 如果您往后在宿主机上遇到了 **Power Keys** 的其他问题，请尽管提出，我们一起找原因。 😄

嗯嗯，好的，谢谢！

我主要是宿主机用得多，还是不能开游戏模式的，在虚拟机里开了游戏1模式<<<----呃，说着说着在宿主机也出现了 😂
