### ISSUE TITLE
* /,Not easy to press

### ISSUE THREAD

**Issue by zhouyong3226429** [szzhiyang/PerfectWindows#67]
* /,Not easy to press

**Comment by szzhiyang** [comment]
@zhouyong3226429 

Which key mappings for `*` and `/` do you prefer? Please let me know.

**Comment by zhouyong3226429** [comment]
The mapping key of the previous version is very good. For example: 9 corresponds to -; 7 corresponds /

**Comment by zhouyong3226429** [comment]
> @ zhouyong3226429
> 
> 哪个键映射`*`和`/`你喜欢哪个？请告诉我。

The mapping key of the previous version is very good. For example: 9 corresponds to -; 7 corresponds /

**Comment by szzhiyang** [comment]
@zhouyong3226429 

**I have already reverted the previous key mappings. Enjoy!** 😄

**Comment by zhouyong3226429** [comment]
Thank you very much for the surprise。

**Comment by szzhiyang** [comment]
@zhouyong3226429 

u r welcome! 😄
