### ISSUE TITLE
吐槽和建议

### ISSUE THREAD

**Issue by hex11** [szzhiyang/PerfectWindows#7]
看到了您的 [这条评论](https://github.com/Snipaste/feedback/issues/818#issuecomment-363503236)，我就点开了您的项目。
发现一些默认启用甚至无法配置的功能就是不尊重 Microsoft 嘛。

# 吐槽
readme 里写了 11 个功能：

1. 去除广告[**无配置项**]：
    * 我表示喜闻乐见🌝。（但是这是不尊重 Microsoft 吧）

2. 禁用 Cortana、OneDrive、锁屏、Windows Defender 以及 Windows 自动更新。[默认不禁止]：
    * 还行，我可能会启用一部分（滑稽）。

3. 把某 5 个按键的功能替换为媒体键。[默认不启用]：
    * 我绝对不会用，因为 **其中 4 个按键就是我常用的按键 (Home, End, PgUp, PgDn)**。

4. 自动在 AC/DC 时切换到 高性能/节能 电源计划）[默认不启用]：
    * 没有什么用，因为本来电源计划里就分了 AC/DC。
      （好像这个脚本就是这么实现的？这好像与功能描述不符啊）

5. 使用传统图片查看器。[**无配置项**]：
    * 我觉得自带的那个 UWP 应用挺好用，而且不慢。（而且记得传统查看器缩放图片不够方便）

6. 让任务栏更透明。[**无配置项**]：
    * 不知道是什么效果，不过我觉得现在够透明了。

7. 滚轮“自然滚动”，其实就是反向滚动)[默认不启用]：
    * 我不习惯。还好默认不启用。

8. 一个帮你启动 notepad 编辑 host 并 flush dns 的脚本：
    * 不错，与其他功能相比而言。

9. 使 Edge 与 IE 书签保持一致。[默认不启用]：
    * 我只想说，Firefox 大法好！（[立即下载](https://www.mozilla.org/firefox/new/)）

10. **「通过禁用 Superfetch、家庭组、程序兼容性助手服务、磁盘碎片整理计划任务和自动维护计划任务来加速 Windows。」**[**无配置项**]：
    * 先让我冷静一下……
    * 有一种看到辣鸡教程的感觉；
    * 禁用 superfetch、碎片整理和自动维护会 **减速** Windows；
      【可能你有时候会发现它们占用资源，但是它们都是以 **低 CPU/IO 优先级** 运行的，对其他任务的影响不大（反正我没感觉出来 ~~，可能是因为我用 SSD（逃~~ ）】
    * 禁用家庭组……**您是认为没人用这个功能吗？**
      （虽然我也觉得没人用，至少是在这堆脚本的用户里没人用🌝）
      （**就像 Snipaste 作者认为用户不会用到 F1 和 F3 一样，但是 Snipaste 的设置很容易改啊**）
      （**您还要「贬 Snipaste 的默认热键设置」吗？**）

11. **加固 Windows**。[**无配置项**]：
    * 防止我双击运行压缩包中的可执行文件？？？
    * 禁止从可移动存储设备运行可执行文件？？？
    * 在每个盘符下创建叫 `Checkpoint` 的文件夹，作为「禁运区域」（禁止运行区域）？？？
    * 再让我冷静一下……
    * 360 需要您。

（写到这里，发现 **居然有 5 个“功能”是不能关掉的**，其中 2 个我认为是辣鸡功能）
（欢迎指出错误）

## 结论
我选择 dism++。

# 建议
可以把这东西做成单个 bat，第一次运行时释放那些文件名带 [ X ] [ O ] 的文件。

**Comment by szzhiyang** [comment]
我现在陷入了一个窘境，稀少的设置项会干预用户的意志，繁多的设置项又很容易让人抓狂。:joy:

**Comment by szzhiyang** [comment]
这实在是个硬伤，至今我都没能找到那个平衡点。

**Comment by szzhiyang** [comment]
我现在最迫切的问题就是如何有条不紊地安排这么多的设置项。如果我能解开这个矛盾，您所提及的问题均不再是问题。

您有什么好的主意吗？

**Comment by szzhiyang** [comment]
重新梳理了一下您的建议，似乎您很希望让家庭组成为一个选项，我已经把它加上了。

**Comment by hex11** [comment]
我不会禁用任何 Windows 服务，
除非我知道某个服务是印度人写的，我就会禁用它（笑）。

**Comment by szzhiyang** [comment]
您就这样嘲讽印度人？

**Comment by szzhiyang** [comment]
另外我是拿带有机械硬盘的电脑测试批处理的，那几个优化是真的有效。

另外，Superfetch 对 SSD 而言没有启用的意义。

**Comment by hex11** [comment]
这就有意思了，难道巨硬没测试过吗（

**Comment by szzhiyang** [comment]
所以您还是希望 Superfetch 和那两个计划任务成为选项？

**Comment by szzhiyang** [comment]
# 我放弃了。
