### ISSUE TITLE
如何为每个快捷键添加注释？

### ISSUE THREAD

**Issue by rockbenben** [szzhiyang/PerfectWindows#71]
有了F1~F12的扩展快捷键，极大的扩展了操作效率。

但字母太多后，无法立即分不清具体对应那边快捷键。
建议快捷键只取第一个字符，后方文字可以添加备注
![image](https://user-images.githubusercontent.com/28252913/46901516-3c0cb380-cee8-11e8-8093-26cde118fcd6.png)

**Comment by szzhiyang** [comment]
@rockbenben 

非常感谢您对我的创意的认可！

您可以通过快捷方式的属性面板为其添加备注。

简单调整一下文件资源管理器的查看方式，就可以达到如下图所示的效果：

<br>

![demo3](https://user-images.githubusercontent.com/30952626/46904169-aaff0200-cf12-11e8-8300-a1d8c3a2cf66.png)

**Comment by szzhiyang** [comment]
@rockbenben 

我重新打开了该 issue，这样后面有同样疑问的朋友也能看到它并得到解答，望您理解！

**Comment by szzhiyang** [comment]
@rockbenben 

您好，该 issue 所涉及的「为快捷键添加注释」的技巧已补充进 **Power Keys** 的帮助文档中，因此该 issue 已被关闭，感谢您的支持和理解。
