### ISSUE TITLE
Win + L 偶尔导致鼠标冻结

### ISSUE THREAD

**Issue by zh60171** [szzhiyang/PerfectWindows#72]
系统：win10 64位 专业版
在系统待机及powerKey后台运行的情况下，win+L锁屏一段时间后重新输入密码打开锁屏，有一定几率出现鼠标只能移动，左中右键均无法点击的bug，通过ctrl+alt+del呼出任务管理器后鼠标恢复正常

**Comment by szzhiyang** [comment]
@zh60171 

您好，请问最新版本的 Power Keys 还有这个问题吗？我之前对 **`Win + L`** 的这个问题做过专门的应对措施。

**Comment by szzhiyang** [comment]
@zh60171 

您好，由于您长时间未跟进，此 issue 已被关闭。如需回复，请重新打开它，谢谢。

**Comment by zh60171** [comment]
> 
> 
> @zh60171
> 
> 您好，请问最新版本的 Power Keys 还有这个问题吗？我之前对 **`Win + L`** 的这个问题做过专门的应对措施。

经过一段时间的测试，新版本已无此bug

**Comment by szzhiyang** [comment]
@zh60171 

非常感谢！
