### ISSUE TITLE
允许自定义快捷方式存储目录至同步盘，以便同步多台电脑的快捷键配置

### ISSUE THREAD

**Issue by centaur0629** [szzhiyang/PerfectWindows#73]
提一个建议, 能否将设置的目录F1-F12的文件夹, 可以自定义设置一个目录

比如我经常会用同步的网盘,  我有多台电脑,   每台电脑上会安装很多的软件,  目录都差不多一致的

这样放到云上同步 , 就更好了

**Comment by szzhiyang** [comment]
@centaur0629 

您好，非常感谢您对 Power Keys 的认可和建议！

事实上，作为 OneDrive 的忠实用户，当初我在构想 Power Keys 的功能时，也就是我在开始着手编写 Power Keys 的代码之前，我就已经考虑到同步盘的事情了。很快，我就发现了一个这样的问题：

**当我们需要在不同电脑上对相同的快捷键指定不同的快捷方式时，我们该怎么办呢？**

就拿我自己的例子来说，我有一台运行 64 位 Windows 和 Nvidia GeForce 显卡的笔记本电脑和一台运行 32 位 Windows 和 AMD Radeon 显卡的台式电脑，我希望在任一电脑上都能用相同的快捷键来启动 Office 的各个组件以及显卡设置面板。

然而，我的笔记本电脑上的 Office 安装在 `C:\Program Files(x86)` 中，但是我的台式电脑上的 Office 安装在 `C:\Program Files` 中，并且两台电脑的显卡设置面板还完全不一样。如果用网盘同步两台电脑的快捷方式，就意味着我只能同步两台电脑中某一台所使用的快捷方式，而这就很不方便了。

后面我也想了好几个解决方法，不过它们都会让快捷键的配置过程变得相当复杂，整体的流程和逻辑还不如复制粘贴来得简单直接，于是我就没有做这样的功能了。

您能跟我一起想想上述的问题的解决方法吗？如果有简单的方法能完美处理同步时的特例情况，那这个同步功能我肯定能加上去。

**Comment by centaur0629** [comment]
哈哈,  先握个爪,   我也是OneDrive的忠实用户,  顺便鄙视一下其它同步盘先^_^

 对于这个问题, 明白了您的问题思路,  咱们分开来解:

1. 首先是绿色软件,  作为绿色软件的狂热者 , 能用绿色绝不安装的心态,   我会把很多绿色的小软件都会放到同步盘上, 这样换终端都会很方便的;   比如我会在每一台终端上都会设置放到 D:/OneDrive,  所以对于绿色版软件都 放到同步盘来说,   真的很需要将目录自定义哈; 

2. 您说的问题,  可能都是发生在安装型的软件上, 我觉得有一个思路可以借鉴, 就是运行命令行的方式
![image](https://user-images.githubusercontent.com/15000148/47401472-1dbe7780-d774-11e8-9b22-a21434f0b222.png)

作为 Altrun的用户, 可以支持命令行的方式 , 可以很方便调用, 
![image](https://user-images.githubusercontent.com/15000148/47401514-56f6e780-d774-11e8-83f6-0ffddba14c33.png)
对于国外的大型软件都可以通过命令行运行的, 
比如 Word , 通过命令行  winword
Excel,  通过命令行  excel
Photoshop,  通过命令行 photoshop ,  
![image](https://user-images.githubusercontent.com/15000148/47401704-0764eb80-d775-11e8-9bb5-4f605f5ef8ab.png)

都是可以启动的,  并不一定需要和目录有关系;

3. 最后还有一部分软件,  比如是大多数国产的安装型软件了,  他们很多由于没有写到注册表或者服务里, 没办法通过命令行的方式来运行,  像这类软件一般也都能选择自己的安装目录,  比如我自己都会将一些国产的安装型软件都会安装到D:/Program Files里,  这样不管是哪台电脑上,  都可以通过快捷方式调用的;

我认为,  一个严谨的人, 会把自己的软件和文件也都安排得井井有条, 每一台电脑上文件存放都会有有相同的习惯,   如果一个太过随意的人,  软件和文件到处乱放,  任何快捷方式管理工具, 恐怕都没办法来解决这个问题吧;

**Comment by szzhiyang** [comment]
@centaur0629 

非常感谢您深入细致的分析！ 😄 

诚如您所说，严谨的人会尽可能让每台电脑上应用程序的安装和存储逻辑一致（其实我也是这么做的 😂 ），但是凡事总是有特例，就像我在上文所提到的两台电脑使用不同显卡的情况，的确没办法用您所述的几种方法来解决。

---

**其实，不同电脑的不同用途和不同硬件情况非常容易催生在不同电脑上用相同快捷键启动完全不同的应用程序的需求，这是绝对不能忽视的情况。**

举个例子，一个同时拥有一台支持触屏和手写笔的笔记本电脑和一台不支持触屏或手写笔的台式电脑的人，可能就希望在前者上用 **`F1 + N`** 启动更适合触屏和手写笔使用的 UWP 版本 OneNote，在后者上用 **`F1 + N`** 启动功能更强大且更适合鼠标使用的传统 Win32 版本的 OneNote 2016，然而您所述的几种解决方法都无法处理这样的情况。

---

不同电脑的使用差异是难以避免和消除的，所以我们需要想个办法完美解决好同步过程中所产生的这个问题，您有什么好的办法来解决我上面举的例子中的问题吗？

**Comment by centaur0629** [comment]
额,  举的这个例子可能不太恰当额,  我认为的 UWP的 OneNote和 OneNote 2016本质上是两个不同的程序,  所以理所当然的是两个不同的快捷方式,   这个就有必要教育用户,  说明清楚;

有时候我电脑上也经常会安装同一个程序的的不同版本,  这个也是非常常见的场景,  但我觉得不同版本的程序本质上不是同一个程序,  要把他们理解成两个不同个体,   我必须得用两个快捷方式来调用; 

如果非要用一个快捷方式自动调用哪个版本的,  我觉得这个可能不如先问问用户自己的大脑, 不能单纯的靠机器来判断吧 ?

**Comment by szzhiyang** [comment]
@centaur0629 

但是如果不同的程序只能用不同的快捷方式来启动，就有可能造成快捷键的浪费和逻辑混乱，还会降低设置快捷键的自由度，我们一起想一个鱼和熊掌均可兼得的解决方案吧。 😃

**Comment by szzhiyang** [comment]
@centaur0629 

我最近几天又做了尝试，不过还是没有找到能够轻松处理同步特例的方法，如果您想到了可行的解决方案，请打开该 issue 并告诉我好吗？非常感谢！
