### ISSUE TITLE
F2 重命名功能失效

### ISSUE THREAD

**Issue by lindefoe** [szzhiyang/PerfectWindows#74]

**Comment by szzhiyang** [comment]
@lindefoe 

**Power Keys** 有一套犹豫处理机制。如果您按住 **`F1`** ~ **`F12`** 0.3 秒以上，Power Keys 就会视您的操作为犹豫操作而不响应。因此，当您需要重命名文件时，请不要长按 **`F2`** 太久，否则就会触发 **Power Keys** 的犹豫处理机制。

**Comment by szzhiyang** [comment]
@lindefoe 

另外，这个问题也有可能是您的杀毒软件的影响导致的，建议您将 **Power Keys** 主程序添加到杀毒软件的白名单中。

**Comment by lindefoe** [comment]
回复很快点个赞！
恩，一开始下载这个软件就已经把他加入白名单了，但是还是会有这个情况。
0.3秒很短，基本是没办法单触发这一个按键，
其实如果重命名能使用f2的组合键代替，也是个不错的选择，但是重命名的编写方式是怎样的呢

**Comment by szzhiyang** [comment]
@lindefoe 

不好意思，我重新看了下代码，那个超时不是 0.3 秒，而是 0.5 秒，我把这个超时和另外一个超时记混了。 😂 

![image](https://user-images.githubusercontent.com/30952626/47724513-ccd9e200-dc91-11e8-9a55-3016da3591f9.png)

0.5 秒真的已经很久了，也许可能是另外的原因导致了您的问题。

重命名的 **`AutoHotkey`** 实现代码是：**`Send {F2}`**。

**Comment by Primers-cern** [comment]
昨天开始同样遇到这样的问题。
F1键F2键失效（有设置组合），~键1键都无法输入（非组合），
但是组合键时可以使用，退出powerkey后恢复正常。
重启更新均未能解决。

**Comment by szzhiyang** [comment]
@Primers-cern 

请问退出杀毒软件后还有这样的问题吗？

请问您有运行跟 **Power Keys** 同类型的键盘脚本软件吗？

**Comment by szzhiyang** [comment]
@Primers-cern 

感谢您的理解与支持！

我已经在下载链接处添加了有关杀毒软件误报的提示：

![image](https://user-images.githubusercontent.com/30952626/48252676-4f0b9880-e440-11e8-82fd-33c2cac8df8d.png)

**Comment by SanLyn** [comment]
虚拟桌面切换后有时会出现默认win键或tab键为按下的状态，在长时间运行后虚拟桌面切换功能会失效，power keys自身的重启对上述问题无效，只能退出后重新启动；长时间运行后已设置快捷方式的数字键（字母未确认）和`键也会失效（已加入至白名单，仅长时间运行后会出现），退出后重新启动恢复正常

**Comment by SanLyn** [comment]
虚拟桌面切换后有时会出现默认win键或tab键为按下的状态，在长时间运行后虚拟桌面切换功能会失效，power keys自身的重启对上述问题无效，只能退出后重新启动；长时间运行后已设置快捷方式的数字键（字母未确认）和`键也会失效（已加入至白名单，仅长时间运行后会出现），退出后重新启动恢复正常
