### ISSUE TITLE
1803 17314.285 禁用失效

### ISSUE THREAD

**Issue by PlasticLie** [szzhiyang/PerfectWindows#75]
家庭版，1803 17314.285版本运行本软件以后仍然在我没有主动检查更新的情况下安装了更新。

**Comment by szzhiyang** [comment]
@PlasticLie 

您好，在您下载使用 **Anti Windows Update** 之前，Windows 是否已经有挂起的更新？为了避免引起 Windows 系统文件损坏，**Anti Windows Update** 是不会阻拦 Windows 应用已经挂起的更新包的。

**Comment by szzhiyang** [comment]
@PlasticLie 

您好，由于您长时间未跟进，此 issue 已被关闭。如有需要，请重新打开该 issue，感谢。
