### ISSUE TITLE
屏蔽功能更新，但放行安全更新

### ISSUE THREAD

**Issue by i5151** [szzhiyang/PerfectWindows#76]
我们讨厌的就是微软自作主张强推的大版本更新，但其他的更新还是很有必要的。如果阻止了所有的更新，都手动更新的话，效率有点低，而且容易遗忘。

**Comment by szzhiyang** [comment]
@i5151 

我暂时还不知道怎么做到这一点。 😂

**Comment by i5151** [comment]
> @i5151
> 
> 我暂时还不知道怎么做到这一点。 😂

相信你能做到！

**Comment by szzhiyang** [comment]
@i5151 

好的好的，我再想想办法。 😂

**Comment by Javier0731** [comment]
安全补丁、当前版本累计更新及大版本更新，都能用用dism++管理啊，作者难不成还要帮各位理清每个补丁的作用？
