### ISSUE TITLE
一个屏蔽更新失效的可能原因

### ISSUE THREAD

**Issue by PlasticLie** [szzhiyang/PerfectWindows#77]
我曾经打开了anti Windows update，他也一周都很安静没有提示更新，然而就在我在商店下载了一个应用以后，他就更新了。

是不是说商店下东西也属于“手动检查更新”范畴？

**Comment by szzhiyang** [comment]
@PlasticLie 

不属于的，我每天都会检查 Microsoft Store 应用程序的更新，但是 Windows Update 一直都没有动静。

**Comment by netwmr01** [comment]
Anti Windows update   好像失效了好几个月了，不知道作者大大上次提到的大招有着落了吗？ @szzhiyang
