### ISSUE TITLE
最近在使用时候偶尔会碰到强制输入Ctrl键的情况

### ISSUE THREAD

**Issue by Night8848** [szzhiyang/PerfectWindows#78]
某些时候（我并不能确定是那种具体的情况下）它会产生错误，使得会强制输入Ctrl键，在重新打开关闭游戏模式后会恢复正常。

**Comment by szzhiyang** [comment]
@Night8848 

感谢您的反馈！我检查了 **Power Keys** 涉及到 **`Ctrl`** 键的代码，并没有发现什么逻辑上的问题，并且我之前也没有遇到过误发送 **`Ctrl`** 键的情况，所以这可能是遇到不明冲突的结果，我会尽可能想办法解决的。

**Comment by szzhiyang** [comment]
@Night8848 

您好，麻烦您更新到最新的 **`9.3.5`** 版本，看看这个问题是否得到解决，谢谢！

**Comment by szzhiyang** [comment]
@Night8848 

您好，麻烦您更新到最新的 **`9.3.6`** 版本，看看这个问题是否得到解决，谢谢！

**Comment by Oilj** [comment]
> @Night8848
> 
> 感谢您的反馈！我检查了 **Power Keys** 涉及到 **`Ctrl`** 键的代码，并没有发现什么逻辑上的问题，并且我之前也没有遇到过误发送 **`Ctrl`** 键的情况，所以这可能是遇到不明冲突的结果，我会尽可能想办法解决的。

建议考虑该因素 https://www.jianshu.com/p/4157814c2e6f
