### ISSUE TITLE
如何使用快捷键开启/关闭游戏模式？

### ISSUE THREAD

**Issue by WAY29** [szzhiyang/PerfectWindows#79]
如何使用快捷键开启/关闭游戏模式？

**Comment by szzhiyang** [comment]
@WAY29 

您好，仅需按 **`Win + Esc`** 即可开启或关闭 **游戏模式**。

您可以通过 **Power Keys** 的任务栏托盘菜单得知这个快捷键：

<br>

![](https://user-images.githubusercontent.com/30952626/49336338-5a1aa880-f63b-11e8-91ee-7d3cc3089a71.png)

**Comment by WAY29** [comment]
我按了没反应。。。

**Comment by szzhiyang** [comment]
@WAY29 

您确定您使用的是最新版本的 **Power Keys** 吗？如果不确定，请前往 `https://PowerKeys.github.io` 下载并使用最新版本。

**Comment by szzhiyang** [comment]
@WAY29 

那我关闭该 issue 了，如果您后续遇到了什么新的问题，请开新的 issue，谢谢！
