### ISSUE TITLE
注册表操作失败

### ISSUE THREAD

**Issue by Z-fly** [szzhiyang/PerfectWindows#80]
win10 32位 1809
![image](https://user-images.githubusercontent.com/10470892/52162907-4f50c280-2715-11e9-9110-0e0256a8480d.png)

原本目的：单纯想禁用Windows Defender

**Comment by Z-fly** [comment]
顺便想关闭windows安全中心的图标

**Comment by szzhiyang** [comment]
@Z-fly 这说明 **Blacklist.exe** 需要访问和修改的某些注册表键值被某些更高的权限保护起来了。
