### ISSUE TITLE
没有组合键可以模拟delete键吗？

### ISSUE THREAD

**Issue by kmpro** [szzhiyang/PerfectWindows#81]

**Comment by szzhiyang** [comment]
@kmpro 

你好，**Power Keys** 的 **空格编辑** 功能中有 **`Delete`** 键位，请留意键位图的右上角：

![](https://user-images.githubusercontent.com/30952626/48669284-3e43dc80-eb3c-11e8-89ab-2669c4ee4058.png)

如果没有其他问题，请关闭此 issue，多谢。
