### ISSUE TITLE
建议自动检测全屏D3D窗口以启用游戏模式。

### ISSUE THREAD

**Issue by wdhwg001** [szzhiyang/PerfectWindows#83]
有时候经常忘了启动游戏模式，如果能自动检测全屏的D3D窗口就好了。

**Comment by wdhwg001** [comment]
相关资源: 
https://stackoverflow.com/questions/3536373/detect-if-user-has-any-application-running-in-fullscreen
https://docs.microsoft.com/zh-cn/windows/desktop/api/d3d9helper/nf-d3d9helper-idirect3ddevice9-testcooperativelevel

**Comment by szzhiyang** [comment]
@wdhwg001 感谢，但是这样的检测方法并不通用，很容易出现误判和漏判的情况。
