### ISSUE TITLE
建议允许设置空格编辑的最短长按空格时间。

### ISSUE THREAD

**Issue by wdhwg001** [szzhiyang/PerfectWindows#85]
在正常输入英文的时候，我注意到我经常因为出现“按下空格→输入下一个字母→松开空格”这样的粘滞操作导致错误的激活了快捷键。
或许，允许设置空格编辑的最短激活时间可以改善这个状况。

**Comment by szzhiyang** [comment]
@wdhwg001 这个激活超时是精心考量过的，长了就会影响文本编辑的效率和连贯性。如果你经常遇到这样的情况，建议你打字敲击空格时更干脆利落些。

**Comment by wdhwg001** [comment]
@szzhiyang 事实上空格黏滞的状况取决于键盘的键程和按键在键程中的触发位置，这是因人而异的。
而且改变输入习惯是困难的。比如，在qwerty键盘中文输入时，准确区分ng和gn(如ting和tign)也是一个“只需要干净利落些”但却很难做到无误的事情。
所以，硬编码的最小延时或许不能应对所有需求。

**Comment by szzhiyang** [comment]
@wdhwg001 我再考虑一下吧。
