### ISSUE TITLE
增大/减小 系统音量失效

### ISSUE THREAD

**Issue by rpishgithub** [szzhiyang/PerfectWindows#86]
最新版Win10下，使用WIN + “+” 或者WIN + “-”不能更改系统音量。
WIN + “\”正常工作 可以设置静音。
但是WIN + “+” 或者WIN + “-” 受到系统放大镜影响不能正常工作。

**Comment by szzhiyang** [comment]
@rpishgithub 我这边一切正常。你用的是最新版的 **Power Keys** 吗？你用的是预览版的 Windows 吗？
