### ISSUE TITLE
可以附上功能说明么？另外附上个类似得项目

### ISSUE THREAD

**Issue by laincat** [szzhiyang/PerfectWindows#9]
有一个类似得项目：https://github.com/CHEF-KOCH/regtweaks

**Comment by szzhiyang** [comment]
当然可以。事实上我昨天才把这个页面做出来。:joy:

另外，我的这些小软件远不止改个注册表那样简单，里面还蕴含着更多值得发掘和扩展的方面。:smile:

**Comment by szzhiyang** [comment]
**Power Keys** 和 **Checkpoint** 都是我自己的创意哦。:smile:

**Comment by laincat** [comment]
很赞！很方便！愿越来越好~！
